spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codegame?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    username: root
    password: codegame2021

  #db configuration
  #spring.
  jpa:
    #spring.jpa.
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
      jdbc:
        batch_size: 500
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    #spring.jpa.
    hibernate:
      naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none

    #spring.jpa
    generate-ddl: false
    open-in-view: false
    show-sql: true

  #spring.mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: tule.java@gmail.com
    password: 9781695123aB!
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# tomcat server config
server:
  port:
    9129
  tomcat:
    max-threads: 10
    min-spare-threads: 5

#JWT athentication
security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: 86400
    inbound_secret: 31977626-cac4-4e8f-906c-678911baa430
    shared_secret: 31977626-cac4-4e8f-906c-678911baa430
    shared_expire_after: 1440
    shared_client_id: 5c0fa4f4-2051-4999-8db8-78b95f48409b

logging.level.org.springframework.web.filter.RequestLogginFilter: DEBUG


  #enable mapping json to enum type on object field
  #spring.jackson.mapper.accept-case-insensitive-enums=true

